# Generated by `cargo xtask homebrew-formula`; do not edit by hand.
class Qq < Formula
  desc "AI coding agents in one binary"
  homepage "https://github.com/retsu-AI/qq"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/retsu-AI/qq/releases/download/v0.1.4/qq-v0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "15b5fb58f16dd74fefce6664b82c4f253582a24ccdb5ff711bcc3b2a70b52591"
    end
    on_intel do
      url "https://github.com/retsu-AI/qq/releases/download/v0.1.4/qq-v0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "4e40fea5e28a09568a3d343dc8001b88dd119548a3165b2f638c213da8c05048"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/retsu-AI/qq/releases/download/v0.1.4/qq-v0.1.4-aarch64-unknown-linux-musl.tar.gz"
      sha256 "0f99ecbfb8863d391bcbc92763071e01867fc3c6c94fbe78da8c61e9e1c7d7e6"
    end
    on_intel do
      url "https://github.com/retsu-AI/qq/releases/download/v0.1.4/qq-v0.1.4-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c1815d2f970062c350286292cedeb0df8800b5d728e3fb82c89c270fdf774e11"
    end
  end

  def install
    bin.install "qq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qq --version")
  end
end
